### ISSUE TITLE
Uncommon camelCase method names

### ISSUE THREAD

**Issue by mmichaa** [davispuh/TimezoneParser#2]
Hi @davispuh,

at first I want to thank you for this gem 👍  Today I used it the first time. In the Ruby World it's uncommon to name methods in camelCase. It's even uncommon to prefix method names with _get_ or _set_. So, for example, `getOffsets` should be names just `offsets`.
Maybe you could rename them to the common format. But to be backwards compatible for you could set aliases but mark them as deprecated. Just a suggestion.

Best regards.

**Comment by davispuh** [comment]
I know this, but I don't really consider it that important and I personally prefer it this way.
